import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Head from "next/head";
import { Sidebar } from "~/components/Sidebar";
import { SessionProvider } from "next-auth/react";
import Providers from "~/components/Providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Twitter clone",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <Providers>
            <div className="container mx-auto flex items-start sm:pr-4">
              <Sidebar />
              <div className="min-h-screen flex-grow border-x">{children}</div>
              <Sidebar />
            </div>
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
